### ISSUE TITLE
后台的用户名跟密码是什么

### ISSUE THREAD

**Issue by ljkfgh2008** [cong25825933/autoexam_system#1]
如题

**Comment by ljkfgh2008** [comment]
还有需要的java版本和数据库版本呢

**Comment by imcuttle** [comment]
该项目已经不继续维护了

**Comment by ljkfgh2008** [comment]
那能提供一下运行环境么

**Comment by imcuttle** [comment]
JAVA8，tomcat>=7，MySQL>=5.7就行

**Comment by ljkfgh2008** [comment]
不好意思 又打扰你 请问后台登录的账号密码是多少

**Comment by ljkfgh2008** [comment]
请问文件导入的excel 格式是什么样的 能提供一下么

**Comment by imcuttle** [comment]
.....不好意思好像丢失了

**Comment by ljkfgh2008** [comment]
有特殊的格式么 或者什么 能帮忙想一下么 麻烦了

**Comment by imcuttle** [comment]
https://github.com/moyuyc/autoexam_system/blob/master/src/top/moyuyc/transaction/ExcelAcess.java    看下这个代码，  直接用这个代码批量导入的
