### ISSUE TITLE
无法读取试题

### ISSUE THREAD

**Issue by ljkfgh2008** [cong25825933/autoexam_system#3]
也不报错 但是点击读取试卷的时候 无法读取 考试科目也是问号

**Comment by imcuttle** [comment]
你数据库中有题目么

**Comment by ljkfgh2008** [comment]
数据库里有的 试题也添加了 但是前台读取的时候就有问题

**Comment by ljkfgh2008** [comment]
![image](https://cloud.githubusercontent.com/assets/5298951/23002325/13cfaac0-f425-11e6-9503-2e76b759e76d.png)
 就是这种状态

**Comment by imcuttle** [comment]
1. 数据库是不是 utf-8 编码
2. 代码文件是不是 utf-8 编码
3. 项目中的 exam.sql 中已有的题目是不是乱码

**Comment by ljkfgh2008** [comment]
经过一早上修改题目可以读了 但是提交试卷跟查看考试记录 页面就会卡死 是不是js存在问题

**Comment by imcuttle** [comment]
不是的，线上地址你可以试下看  http://moyuyc.xyz/autoexam

**Comment by ljkfgh2008** [comment]
线上的是好的 我本地部署了 就不知道什么问题了

**Comment by imcuttle** [comment]
十有八九是  java运行错误了
