### ISSUE TITLE
【HELP】貌似网址访问不了。。。

### ISSUE THREAD

**Issue by JayVae** [cong25825933/autoexam_system#4]
@imcuttle 冒昧打扰到您，但是貌似您的网址访问不了。。
显示一串看不懂的文字（￣□￣｜｜）

**Comment by imcuttle** [comment]
你好，线上地址是好久之前搭建的，你可以clone代码至本地运行，部分界面截图[在这](https://imcuttle.github.io/talk-about-websocket)可以找到

**Comment by JayVae** [comment]
@imcuttle 多谢 很棒的工作！
